version: 0.0
os: linux
files:
  - source: /
    destination: /tmp
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
    - location: scripts/start_client
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/start_stop
      timeout: 300
      runas: root
